### PR TITLE
feat: added new pages

### PR DESCRIPTION
**Pull request by Ngozi-Txfusion**
### What

- **Added Installation Page for zkSync-Ethers JS SDK:**
  - Created a detailed installation guide for the zkSync-Ethers JavaScript SDK, providing step-by-step instructions on how to set up the SDK for developers.
  
- **Added "Why zkSync-Ethers JS SDK" Page:**
  - Developed a new page explaining the benefits and unique features of using the zkSync-Ethers JavaScript SDK, aimed at helping developers understand its advantages and use cases.
  
- **Updated the Overview Page:**
  - Made comprehensive updates to the overview page to reflect the latest features and improvements in the zkSync-Ethers SDK, ensuring that the content is up-to-date and informative.

### Why

- **Installation Page:**
  - To provide developers with a clear and concise guide on how to install and configure the zkSync-Ethers JavaScript SDK, reducing the learning curve and helping them get started quickly.

- **"Why zkSync-Ethers JS SDK" Page:**
  - To highlight the key benefits and unique features of the zkSync-Ethers SDK, making it easier for developers to understand why they should choose this SDK for their projects.

- **Overview Page Updates:**
  - To ensure that the overview page accurately represents the current state of the zkSync-Ethers SDK, including new features and improvements, providing developers with the most relevant and useful information.

### CODE REVIEW

**Review by itsacoyote — CHANGES_REQUESTED** [review]
Just one small change requested, everything else looks good.

**Review by petarTxFusion — DISMISSED** [review]

**Review by danijelTxFusion — CHANGES_REQUESTED** [review]
The order of the pages should be like this:

- Overview
- Why `zksync-ethers`
-  Installation

**Comment by Ngozi-Txfusion** [comment]
> The order of the pages should be like this:
> 
> * Overview
> * Why `zksync-ethers`
> * Installation

Done

**Review by danijelTxFusion — APPROVED** [review]

**Review by itsacoyote — APPROVED** [review]
👍🏻

**Pull request merged**
