### PR TITLE
docs: cleanup prep for release

### PR DESCRIPTION
**Pull request by itsacoyote**
# Description

To prepare for release, this PR cleans up some content that are currently "empty". 
- Pages that do not have any content yet are removed from navigation. 
- Cards under the Support section that do not have links are removed. 
- Support link is changed to the SUPPORT.md file.
- Edited Feedback link so that it uses the Feedback github issue form.
- Renamed numbering scheme for content directory to match the preferred syntax.
- Fixed some issues with the Javascript section displaying the v5, v6 and intro pages.
- Edit link changed to main for preparation for release

### CODE REVIEW

**Comment by AlbionaHoti** [comment]
Screenshot 2024-06-05 at 10 42 54
Is it expected for the preview link to fall into this view?

**Comment by AlbionaHoti** [comment]
Screenshot 2024-06-05 at 10 43 50
- double icons for socials, maybe this can be fixed on this PR

**Comment by AlbionaHoti** [comment]
Screenshot 2024-06-05 at 10 44 50
- there's a dash on the title of the site

**Comment by itsacoyote** [comment]
> Screenshot 2024-06-05 at 10 43 50 - double icons for socials, maybe this can be fixed on this PR

Good check, I can remove those

**Comment by itsacoyote** [comment]
> Screenshot 2024-06-05 at 10 42 54 Is it expected for the preview link to fall into this view?

This is for local development purposes, you won't see that on production. Same with the dash on the main page.

**Review by MexicanAce — APPROVED** [review]
LGTM

**Pull request merged**
